
trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: katalonTask@1
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '8.2.5'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey=$(katalon_api_key)'
